export const routePaths = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  PROFILE: "/profile",
  NOTIFICATIONS: "/notifications",
  CATEGORIES: "/categories",
  SOFTWARE_CATEGORY: "/:category",
  SUB_CATEGORY: "/:category/:subCategory",
  PRODUCT_DETAIL: "/:category/:subCategory/:productSlug",
  COMMUNITY: "/:category/:subCategory/:productSlug/community",
  DISPUTES: "/disputes",
  DISPUTE_DETAIL: "/disputes/:disputeId",
  WRITE_REVIEW: "/write-review",
  RESOURCES: "/resources",
  RESOURCES_WEBINARS: "/resources/webinars",
  WEBINAR_DETAIL: "/resources/webinars/:slug",
  RESOURCES_EDGE: "/resources/edge",
  RESOURCES_GUIDES: "/resources/guides",
  RESOURCES_SUCCESS_HUB: "/resources/success-hub",
};
